language: python

python: 3.4

services: rabbitmq

install:
  - pip install contexts colorama
  - python setup.py install

script:
  - run-contexts -v
  - ./doc/make html

deploy:
  provider: pypi
  user: benjamin.hodgson
  password:
    secure: "bJA9NXYhqDgKiMX71YzU3Bq39NgfEi7R7cUoORs73/11ofJzvrFUsnmvw+n90FHru3b1AwZgOxHnlEOPZpQhgKol6BCBgv0HUscjA00dttXs7TO53/c8gqUIkhwlyEbn6+5++kEBTrrVZWjHrTfK6dWKbFA4LspTewvt4p8I9rQ="
  on:
    tags: true
